name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - ipywidgets
  - jupyter_contrib_nbextensions
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
