name: product-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - ipywidgets
  - jupyter_contrib_nbextensions
  - scikit-learn
  - lightgbm
  - missingno
  - mistune
  - mkl-fft
  - mkl-random
  - mkl-service
  - mlflow
  - mlxtend
  - mock
  - more-itertools
  - mpmath
  - msgpack
  - msrest
  - multidict
  - multimethod
  - multipledispatch
  - multiprocess
  - murmurhash
  - mvtpy
  - navigator-updater
  - nbclassic
  - nbclient
  - nbconvert
  - nbdime
  - nbformat
  - nest-asyncio
  - netCDF
  - networkx
  - nltk
  - nose
  - notebook
  - numba
  - numexpr
  - numpy
  - numpydoc
  - nvidia-ml-py
  - oauthlib
  - olefile
  - opencensus
  - opencensus-context
  - opencv-python
  - openpyxl
  - optuna
  - packaging
  - pandas
  - pandas-datareader
  - pandas-profiling
  - pandocfilters
  - panel
  - param
  - paramiko
  - parso
  - partd
  - path
  - pathlib
  - pathos
  - pathtools
  - patsy
  - pbr
  - pdfminersix
  - pdftopng
  - pep
  - pexpect
  - phik
  - pickleshare
  - Pillow
  - pip
  - pkginfo
  - plac
  - plotly
  - pluggy
  - ply
  - pox
  - ppft
  - ppscore
  - preshed
  - prettytable
  - probableparsing
  - prometheus-client
  - prometheus-flask-exporter
  - prompt-toolkit
  - prophet
  - protobuf
  - psutil
  - ptyprocess
  - pure-eval
  - py
  - py-spy
  - pyaml
  - pyasn
  - pyasn-modules
  - pybind
  - pycaret
  - pycodestyle
  - pycosat
  - pycparser
  - pycryptodome
  - pyct
  - pycurl
  - pydantic
  - pydocstyle
  - pyflakes
  - Pygments
  - pyLDAvis
  - pylint
  - PyMeeus
  - PyMySQL
  - PyNaCl
  - pynndescent
  - pyod
  - pyodbc
  - pyOpenSSL
  - pyparsing
  - PyPDF
  - pyperclip
  - pyreadline
  - pyreadline
  - pyrsistent
  - PySocks
  - pystan
  - pytest
  - python-crfsuite
  - python-dateutil
  - python-editor
  - python-jsonrpc-server
  - python-language-server
  - python-stdnum
  - pytz
  - pyviz-comms
  - PyWavelets
  - pywin
  - pywin-ctypes
  - pywinpty
  - PyYAML
  - pyzmq
  - QDarkStyle
  - QtAwesome
  - qtconsole
  - QtPy
  - querystring-parser
  - ray
  - redis
  - regex
  - requests
  - requests-oauthlib
  - retrying
  - rope
  - rsa
  - Rtree
  - ruamel-yaml-conda
  - stransfer
  - sacremoses
  - SALib
  - scikit-image
  - scikit-learn
  - scikit-optimize
  - scikit-plot
  - scipy
  - seaborn
  - SendTrash
  - setuptools
  - setuptools-git
  - shap
  - shapash
  - simplegeneric
  - simplejson
  - singledispatch
  - sip
  - six
  - skope-rules
  - slicer
  - smart-open
  - smartchart
  - smartdb
  - smmap
  - sniffio
  - snowballstemmer
  - some-package
  - sortedcollections
  - sortedcontainers
  - soupsieve
  - spacy
  - Sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sphinxcontrib-websupport
  - spyder
  - spyder-kernels
  - spyne
  - SQLAlchemy
  - sqlparse
  - squarify
  - srsly
  - statsmodels
  - stevedore
  - strsimpy
  - sweetviz
  - sympy
  - tabulate
  - tangled-up-in-unicode
  - tblib
  - tenacity
  - tensorboardX
  - termcolor
  - terminado
  - testpath
  - textblob
  - thinc
  - threadpoolctl
  - tokenizers
  - toml
  - tomlkit
  - toolz
  - torch
  - tornado
  - tqdm
  - traitlets
  - transformers
  - treeinterpreter
  - treelite
  - treelite-runtime
  - tune-sklearn
  - tushare
  - typing
  - typing-extensions
  - ujson
  - umap-learn
  - unicodecsv
  - urllib3
  - usaddress
  - varname
  - visions
  - visualpython
  - waitress
  - Wand
  - wasabi
  - watchdog
  - wcwidth
  - webencodings
  - websocket-client
  - Werkzeug
  - wheel
  - widgetsnbextension
  - win-inet-pton
  - win-unicode-console
  - wincertstore
  - wordcloud
  - wrapt
  - xarray
  - xgboost
  - xlrd
  - XlsxWriter
  - xlwings
  - xlwt
  - xmltodict
  - xmlwitch
  - yapf
  - yarl
  - yellowbrick
  - zict
  - zipp
  - zope.event
  - zope.interface
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
